name: Build

on:
  - push

jobs:
  linux-build:
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          # - ubuntu-18.04
        java:
          - 8
        python-version:
          - 3.6
          - 2.7
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      -
        name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      -
        name: Set up Python
        uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
      - name: Display Java version
        run: java --version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
